workflows:
  deploy_ios:
    name: Deploy to App Store
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: App Elevate Distribution
    triggering:
      events: # List the events that trigger builds
        - tag
      tag_patterns: # Include or exclude watched tag labels
        - pattern: "v*.*.*+*"
          include: true
        - pattern: "v*.*.*+*patch*"
          include: false
    environment:
      ios_signing:
        distribution_type: app_store # or app_store | development | enterprise
        bundle_identifier: cz.appelevate.coree # for wildcard provisional profiles
      flutter: 3.22.3
      xcode: 15.4 # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
      groups:
        # Exports the SHOREBIRD_TOKEN environment variable
        - shorebird
        - sentry
        - fastlane
    scripts:
      - name: Certs
        script: |
          xcode-project use-profiles

      - name: setup flutterfire
        script: |
          dart pub global activate flutterfire_cli

      - name: 🐦 Setup Shorebird
        script: |
          # Install Shorebird
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

          # Add Shorebird to PATH
          echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV

          # Locate your plist file path here, change the file path to match your project
          PLIST_PATH="/Users/builder/export_options.plist"

          if /usr/libexec/PlistBuddy -c "Print :manageAppVersionAndBuildNumber" $PLIST_PATH; then
            echo "Key exists, setting it to false"
            /usr/libexec/PlistBuddy -c "Set :manageAppVersionAndBuildNumber false" $PLIST_PATH
          else
            echo "Key does not exist, adding it and setting it to false"
            /usr/libexec/PlistBuddy -c "Add :manageAppVersionAndBuildNumber bool false" $PLIST_PATH
          fi

      - name: 🚀 Shorebird Release
        script: |
          shorebird release ios --export-options-plist=/Users/builder/export_options.plist --flutter-version=3.22.3 -- --split-debug-info="build/symbolsIos"

      - name: Sign and upload symbols to Sentry
        script: |
          cd ios
          bundle exec fastlane release_ci
          cd ..

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
