name: Review PR

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  review:
    name: Branch name check
    runs-on: ubuntu-latest

    steps:
      - name: Check branch name
        id: check_branch
        run: |
          if [[ ! ${{ github.event.pull_request.head.ref }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Branch name does not match pattern."
            echo "valid=false" >> $GITHUB_ENV
          else
            echo "Branch name is valid."
            echo "valid=true" >> $GITHUB_ENV
          fi

      - name: Close PR and comment
        if: env.valid == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          COMMENT_BODY="Prosím o přejmenování branche, ze kterého je tento PR vytvořen. Název branche musí být ve formátu verze - \`*.*.*\` To je např \`1.11.1\`. Děkuji <3."

          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -X POST \
            -d "{\"body\":\"$COMMENT_BODY\"}" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/comments"

          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -X PATCH \
            -d "{\"state\":\"closed\"}" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER"
          exit 1

      - name: Comment nice
        if: env.valid == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          COMMENT_BODY="Díky za PR! Nyní už jen stačí sehnat někoho kdo ho ověří. Hodně štěstí 🎉"

          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -X POST \
            -d "{\"body\":\"$COMMENT_BODY\"}" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/comments"
