name: "Cleanup artefacts"
on:
  workflow_dispatch:
jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: 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
          expire-in: 7days # Set this to 0 to delete all artifacts
