name: "Cleanup artefacts"
on:
  workflow_dispatch:
jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: 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
          expire-in: 7days # Set this to 0 to delete all artifacts
