name: "Delete old Artifacts"
on:
  workflow_dispatch:
permissions:
  actions: write

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all artifacts
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0 # Setting this to 0 will delete all artifacts
