name: "[DEV] Build and Publish iOS"
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install firebase
        run: curl -sL https://firebase.tools | bash

      - name: install flutterfire
        run: dart pub global activate flutterfire_cli

      - name: Building IPA
        run: flutter build ipa --split-debug-info symbolsIos --obfuscate --release --no-codesign

      - name: Signing the app and publishing to App Store
        run: |
          mkdir -p ios/private_keys
          echo ${{ secrets.IOS_APPSTORE_CERT_BASE64 }} | base64 --decode > ios/private_keys/AuthKey_VPJ6V9H7X3.p8
          cd ios  
          fastlane release
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.IOS_KEYS_PAT }}
          MATCH_PASSWORD: ${{ secrets.IOS_KEYS_MATCH_PASSWORD }}

      # Collect the file and upload as artifact
      - name: collect ipa artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          # Path to the release files
          path: ios/*.ipa

      - name: collect debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: symbols-ios
          # Path to the release files
          path: symbolsIos

      - name: Remove private keys
        if: always()
        run: rm -rf ios/private_keys
