name: Web Cloudflare

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  version:
    name: Create version number and extract applicationId
    # Works only on ubuntu
    runs-on: ubuntu-latest
    outputs:
      app_id: ${{ steps.extract_app_id.outputs.app_id }}
      firebase_id: ${{ steps.firebase_id.outputs.firebase_id }}
      version: ${{ steps.gitversion.outputs.nuGetVersion }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: "5.x"

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.1.1

    - name: Create version.txt with nuGetVersion
      run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt

    - name: Update version in YAML
      run: |
        sed -i "s/^version: .*/version: $(tr -d '\n' < version.txt)+${{ github.run_number }}/" pubspec.yaml

    - name: Upload pubspec.yaml
      uses: actions/upload-artifact@v4
      with:
        name: pubspec
        path: pubspec.yaml

    - name: Get applicationId
      id: extract_app_id
      run: |
        application_id=$(grep -oP 'applicationId\s*=\s*"\K[^"]+' android/app/build.gradle)
        echo "app_id=$application_id"
        echo "app_id=$application_id" >> "$GITHUB_OUTPUT"

    - name: Get Firebase app id
      id: firebase_id
      run: |
        firebase_id=$(jq -r '.client[0].client_info.mobilesdk_app_id' android/app/google-services.json)
        echo "firebase_id=$firebase_id"
        echo "firebase_id=$firebase_id" >> "$GITHUB_OUTPUT"

  build:
    name: Build and deploy web to Cloudflare Pages
    needs: version
    # Works on ubuntu and macOS. Should propably work on windows as well
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Checkout code
      uses: actions/checkout@v4



    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Get peanut
      run: |
        flutter pub global activate peanut

    - name: Setup git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git fetch origin dist-cloudflare-pages:dist-cloudflare-pages || true
        git checkout dist-cloudflare-pages || true
        git checkout main

    - name: Get pubspec
      uses: actions/download-artifact@v4
      with:
        name: pubspec

    - name: Start release build
      run: |
        flutter pub global run peanut -b dist-cloudflare-pages

    - name: Release Artifact Upload
      uses: actions/upload-artifact@v4
      with:
        name: web
        path: build/web
    
    - name: Deploy to Cloudflare Pages
      run: |

        # Push the new branch to the repository
        git push origin dist-cloudflare-pages

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}