name: Symbols upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  version:
    name: Create version number and extract applicationId
    runs-on: ubuntu-latest
    outputs:
      app_id: ${{ steps.extract_app_id.outputs.app_id }}
      firebase_id: ${{ steps.firebase_id.outputs.firebase_id }}
      version: ${{ steps.gitversion.outputs.nuGetVersion }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: "5.x"
    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.1.1
    - name: Create version.txt with nuGetVersion
      run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt
    - name: Update version in YAML
      run: |
        sed -i "s/^version: .*/version: $(tr -d '\n' < version.txt)+${{ github.run_number }}/" pubspec.yaml
    - name: Upload pubspec.yaml
      uses: actions/upload-artifact@v4
      with:
        name: pubspec
        path: pubspec.yaml

    - name: Get applicationId
      id: extract_app_id
      run: |
        application_id=$(grep -oP 'applicationId\s*=\s*"\K[^"]+' android/app/build.gradle)
        echo "app_id=$application_id"
        echo "app_id=$application_id" >> "$GITHUB_OUTPUT"
    - name: Get Firebase app id
      id: firebase_id
      run: |
        firebase_id=$(jq -r '.client[0].client_info.mobilesdk_app_id' android/app/google-services.json)
        echo "firebase_id=$firebase_id"
        echo "firebase_id=$firebase_id" >> "$GITHUB_OUTPUT"

  symbols:
    name: Upload debug symbols
    environment: Crashalytics
    runs-on: windows-latest
    needs:
    - version
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: echo firebase id
      run: echo ${{needs.version.outputs.firebase_id}}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    
    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ needs.version.outputs.version }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    
    - name: Download Google Service Account Key
      id: CRAHSYLITICS_KEY
      uses: timheuer/base64-to-file@v1.2.4
      with:
        fileName: firebase-key.json
        encodedString: ${{ secrets.CRASHLYTICS_KEY_BASE64 }}
    
    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV

    - name: Upload Crashlytics Symbols
      run: |
        firebase crashlytics:symbols:upload --non-interactive --app=${{needs.version.outputs.firebase_id}} symbolsAndroid     