name: TEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      app_id: ${{ steps.extract_app_id.outputs.app_id }}
    steps:
    - name: Get applicationId
      id: extract_app_id
      run: echo "app_id=hello" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          app_id: ${{needs.job1.outputs.app_id}}
        run: echo "$OUTPUT1"