name: test

on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: create a folder and put files in it
      run: |
        mkdir hello
        echo "Hello, World!" > hello/world.txt
        echo "Hello, World!" > hello/world2.txt
        echo "Hello, World!" > hello/world3.txt
    - name: Upload folder
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: hello
  test2:
    name: Test2
    runs-on: ubuntu-latest
    steps:
    - name: download the folder
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: hello
    - name: list the files
      run: ls hello

    

