name: Approving PRs don't make changes to code
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "android/**"
      - "ios/**"
      - "lib/**"
      - "web/**"
      - "test/**"
      - "pubspec.yaml"
      - "analysis_options.yaml"
jobs:
  test:
    name: Test and analyze
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v4
  build_ios:
    name: Build iOS
    if: false
    runs-on: macos-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
  build_android:
    name: Build Android
    if: false
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    if: false
    needs: test
    steps:
      - uses: actions/checkout@v4
