name: "[TEST] Flutter"

on:
  pull_request:
    branches:
      - main

jobs:
  refuse:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        id: validate
        run: |
          if [[ "${{ github.head_ref }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "match=true" >> $GITHUB_ENV
          else
            echo "match=false" >> $GITHUB_ENV

      - name: Run your job
        if: env.match == 'true'
        run: echo "Job is running from branch ${{ github.head_ref }}"
  filter:
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.filter.outputs.android }}
      ios: ${{ steps.filter.outputs.ios }}
      lib: ${{ steps.filter.outputs.lib }}
      web: ${{ steps.filter.outputs.web }}
      test: ${{ steps.filter.outputs.test }}
    steps:
      - uses: actions/checkout@v4
      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            android:
              - 'android/**'
            ios:
              - 'ios/**'
            web:
              - 'web/**'
            lib:
              - 'lib/**'
              - 'pubspec.yaml'
            test:
              - 'test/**'
              - 'analysis_options.yaml'

  test:
    name: Test and analyze
    needs: filter
    runs-on: ubuntu-latest
    if: ${{ needs.filter.outputs.android == 'true' || needs.filter.outputs.ios == 'true' || needs.filter.outputs.lib == 'true' || needs.filter.outputs.web == 'true' || needs.filter.outputs.test == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test

  build_ios:
    name: Build iOS
    runs-on: macos-latest
    needs: test
    if: ${{ needs.filter.outputs.ios == 'true' || needs.filter.outputs.lib == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Build iOS
        run: flutter build ipa --release --no-codesign

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.filter.outputs.android == 'true' || needs.filter.outputs.lib == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17.x"
          cache: "gradle"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Build Android
        run: flutter build appbundle -PuseDebugSigningConfig=true --release

  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.filter.outputs.web == 'true' || needs.filter.outputs.lib == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Build Web
        run: flutter build web --release
