name: TEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      app_id: ${{ steps.step1.outputs.APPLICATION_ID }}
    steps:
      - id: step1
        run: echo "APPLICATION_ID=hello" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.app_id}}
        run: echo "$OUTPUT1"